### ISSUE TITLE
NPM intellisense not working

### ISSUE THREAD

**Issue by Lorex75** [madskristensen/JSON-Intellisense#15]
Lookong in Fiddler it report it caanot risolve https://typeahead.npmjs.com/search
Maybe the url is no longer working...

**Comment by madskristensen** [comment]
The npm team is reworking search and as a result the URL is down for now. They are working on it

**Comment by tlk** [comment]
I believe npm/newww#103 is related:

> I guess nobody misses typeahead search

**Comment by madskristensen** [comment]
I'll use this url to get the packages https://ac.cnstrc.com/autocomplete/g?autocomplete_key=CD06z4gVeqSXRiDL2ZNK&query=gulp
