### ISSUE TITLE
Erro Bower ECONFLICT

### ISSUE THREAD

**Issue by brunoksato** [madskristensen/JSON-Intellisense#9]
I have a problem when the version conflict, in my case happened in boostrap installing fontello. Output in this case does not send the message to choose which version you want boostrap, installed or that the framework uses, in this case ends up catching the installation, and you end up having to do a manual installation from the console ..

Error: Unable to find suitable ECONFLICT version for bootstrap

**Comment by madskristensen** [comment]
How can this be avoided? What should this extension do in case of conflicts?

**Comment by brunoksato** [comment]
Sorry not use more Visual studio !
